Repository flyve-mdm/docker-environment, pull requests merged in 2018-09, with the labels that each got.

#47 Add glpipath var
  .env
Labels: bug

#50 Add GPG steps
  _posts/static/2018-03-08-how-to-contribute.md
  _posts/static/2018-05-17-workflow.md
Labels: documentation

#53 Add travis support for testing
  .travis.yml
Labels: ci

#48 Authentication digest for fcgi
  docker/apache/httpd-vhosts.conf
  docker/apache/vhost.conf
Labels: bug, dependent

#55 Update of shortcuts script for Flyvemdm
  docker/php/Dockerfile
  docker/php/flyvemdm-test
Labels: refactor
