Repository flyve-mdm/docker-environment, pull requests merged in 2018-07, with the labels that each got.

#31 Change network interface to Mosquitto
  .env
  docker-compose.yml
  docker/php/Dockerfile
  docker/php/cliinstall.sh
  docker/php/custom.ini
  docker/php/testall.sh
  docker/php/testinstall.sh
  docker/php/testone.sh
Labels: ci, test

#33 Create command flyvemdm-test
  docker/php/Dockerfile
  docker/php/flyvemdm-test
  docker/php/testall.sh
  docker/php/testinstall.sh
  docker/php/testone.sh
Labels: ci, dependent, test

#36 Change repo slug for gh-pages
  README.md
  _config.yml
Labels: documentation

#39 Add compatibility matrix
  README.md
Labels: documentation

#40 Remove dashboard articles
  _posts/static/2018-07-13-how-it-works-wd.md
  _posts/static/2018-07-13-installation-wd.md
  _posts/static/2018-07-13-requirements.md
  _posts/static/2018-07-16-how-it-works-pl.md
  _posts/static/2018-07-16-how-to-use-pl.md
  _posts/static/2018-07-16-how-to-use-wd.md
  _posts/static/2018-07-16-installation-pl.md
  howtos/index.html
Labels: documentation

#43 Update command flyvemdm-test
  .env
  docker-compose.yml
  docker/php/Dockerfile
  docker/php/flyvemdm-test
Labels: build, ci
